### ISSUE TITLE
Add a Feature to the YAML file to edit the Bacnet name of the Server  Bacnet Device ID of the server Bacnet Object ID  Bacnet Object Name

### ISSUE THREAD

**Issue by simzik** [RAKWireless/lorawan-bacnet-bridge#2]
The Yaml file shoud also include the following configruation possibilites to make it possible to edit the name and id of the server as well as the object-id of the object.

```
bacnet:
  ip: 127.0.0.12
  mask: 24
  port: 47808
  name: [NAME]
  dev-id: [ID}
devices:
  wisblock-01:
    decode: true
    decoder: cayenne.js
    objects:
      field-001-temperature:
        name: wisblock-01-field-001-temperature
        type: AnalogInputObject
        units: degreesCelsius
        value: 24.3
        id: [ID]
datatypes:
  filename: datatypes.yml
logging:
  level: 20
mqtt:
  port: 1883
  server: localhost
  topic: v3/+/devices/+/up
```

**Comment by xoseperez** [comment]
Hi @simzik 

Added support to set the server name and ID and object IDs on the config.yml file. It's on the master branch. Similar syntax to what you suggested, only `bacnet.dev-id` is `bacnet.id`, example file:

```
bacnet:
  ip: 127.0.0.12
  mask: 24
  port: 47808
  name: LBB
  id: 2097153
devices:
  wisblock-01:
    decode: true
    decoder: cayenne.js
    objects:
      field-001-temperature:
        id: 20001
        name: wisblock-01-field-001-temperature
        type: AnalogInputObject
        units: degreesCelsius
        value: 24.3
datatypes:
  filename: datatypes.yml
logging:
  level: 20
mqtt:
  port: 1883
  server: localhost
  topic: v3/+/devices/+/up
```
